stages:
  - deploy

deploy-to-dev:
  stage: deploy
  image: daxter1987/ubuntu-deploy:1.0.11
  script:
    - cp $SSH_PRIVATE_KEY ~/.ssh/digitalplankton-dev.pem
    - chmod 600 ~/.ssh/digitalplankton-dev.pem
    - npm install
    - cp $ENV_FILE .env
    - npm run build
    - rsync -rave "ssh -i ~/.ssh/digitalplankton-dev.pem -o StrictHostKeyChecking=no" out/ ubuntu@$AWS_SERVER_ADDRESS:/var/www/html -y --delete
  environment:
    name: develop
  only:
    - develop
